### ISSUE TITLE
Also accept AS numbers prefixed with "AS"

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/lagosta#21]
Ideally, both "AS65536" and "65536" should be accepted, or a hint should be provided on the expected notation.

<img width="852" alt="Screenshot 2020-02-16 at 15 24 55" src="https://user-images.githubusercontent.com/3448859/74606422-8c91b380-50d0-11ea-8c30-f193ee8a9fc3.png">

**Comment by enricoberti** [comment]
Closed with https://github.com/NLnetLabs/lagosta/commit/8ec6d6447abfd3a208705779cc8ff24726528b27
