### ISSUE TITLE
Allow naming a parent for easy identification

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/lagosta#23]
The name that the parent assigns can be a random hash. At a certain moment users may not know which is which, so allows people assign a custom name. (may be a backend feature)
<img width="944" alt="Screenshot 2020-02-16 at 15 46 57" src="https://user-images.githubusercontent.com/3448859/74606855-2e66cf80-50d4-11ea-9cd4-04fe68ee2738.png">

**Comment by AlexanderBand** [comment]
Alternatively: currently there is a column with "Kind", which I assume will all be "rfc6492". That seems a bit pointless. Listing the service URI instead would actually help the user identifying the Parent, e.g. "http://localcert.ripe.net/certification/updown"

**Comment by enricoberti** [comment]
Closed with #25
