### ISSUE TITLE
Create CA form does not submit when the enter key is pressed

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/lagosta#29]
**Environment:**
- Krill version: `nlnetlabs/krill:v0.5.0` (Docker image)
- O/S: Ubuntu 20.04
- Browser: Firefox 73.0 (64-bit)

**Unexpected Behaviour:**
On the "Let's start by creating your RPKI Certificate Authority (CA)" page, pressing the enter keyboard key has no effect.

![image](https://user-images.githubusercontent.com/3304436/75254661-f7ce3a80-57e0-11ea-9229-2b022a4b7ecf.png)

**Expected behaviour:**
I was expecting that pressing the enter key on the keyboard would perform the same action as clicking the "Create CA" button in the UI.

Thanks,

Ximon

**Comment by enricoberti** [comment]
Closed by https://github.com/NLnetLabs/lagosta/commit/0142865c496a275a57d9b379eccf4ec1bff7687a
