### ISSUE TITLE
Password warning XKCD link is not clickable

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/lagosta#30]
**Environment:**
- Krill version: `nlnetlabs/krill:v0.5.0` (Docker image)
- O/S: Ubuntu 20.04
- Browser: Firefox 73.0 (64-bit)

**Unexpected Behaviour:**
On the login page entering the password `correct-horse-battery-staple` causes the UI t o display a warning about using the same password as is quoted in the [documentation](https://rpki.readthedocs.io/en/latest/krill/testing.html#setting-up-the-configuration), however the XKCD link is not clickable.

![image](https://user-images.githubusercontent.com/3304436/75255292-f94c3280-57e1-11ea-9a5c-268c9d64be05.png)

**Expected behaviour:**
I expect users would find it easier to understand what this message is about if they can easily view the linked XKCD comic. Having to copy and paste the link into their browser adds more difficulty to a situation in which they they have already attempted a forbidden action.

Thanks,

Ximon

**Comment by enricoberti** [comment]
Closed by https://github.com/NLnetLabs/lagosta/commit/0142865c496a275a57d9b379eccf4ec1bff7687a
