### ISSUE TITLE
Lower banner not visible at 1920x1080 on the view CA page

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/lagosta#31]
**Environment:**
- Krill version: `nlnetlabs/krill:v0.5.0` (Docker image)
- O/S: Ubuntu 20.04
- Browser: Firefox 73.0 (64-bit)

**Unexpected Behaviour:**
The text at the bottom of the Lagosta UI is not visible when running in resolution 1920x1080 and viewing the `/index.html#/cas/myca` page:

![image](https://user-images.githubusercontent.com/3304436/75255589-74ade400-57e2-11ea-959f-4ba2af1e491f.png)

It is however visible on the login and create CA pages.

**Expected Behaviour:**
Size the edit boxes a little smaller such that in this (I believe) common resolution the banner is initially visible. According to https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide almost 20% of desktop users use resolution 1920x1080 as of January 2020.

Thanks,

Ximon

**Comment by enricoberti** [comment]
Thanks for this!
The only way to have it always visible at that resolution (without touching the height of elements) would be positioning it fixed on the screen but I'm pretty against it given there's no specific functionality on the footer itself.

**Comment by ximon18** [comment]
+1 - I would also not want it at a fixed position.
