### ISSUE TITLE
"Parent Request" should be "Child Request" in header

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/lagosta#32]
<img width="1502" alt="krill-ui-child-request copy" src="https://user-images.githubusercontent.com/3448859/75322411-f77e7f80-5872-11ea-83c4-8f04b7de0547.png">

**Comment by enricoberti** [comment]
Closed by https://github.com/NLnetLabs/lagosta/commit/0142865c496a275a57d9b379eccf4ec1bff7687a
