### ISSUE TITLE
Browser refresh always require re-signing in

### ISSUE THREAD

**Issue by dadepo** [NLnetLabs/lagosta#33]
Did a quick search through the issues if this has already been mentioned...

Refreshing the page, always leads to a "sign-out", hence the need to re-sign in.

It would be nicer if this was not the case.

**Comment by enricoberti** [comment]
Thanks @dadepo! We created https://github.com/NLnetLabs/lagosta/issues/34 to actually eliminate the current logic and introduce the concept of timeout

**Comment by enricoberti** [comment]
Fixed with https://github.com/NLnetLabs/lagosta/commit/548c9216167c80de9d5b8b39304c962088cf23ba
