### ISSUE TITLE
Table headers for ROAs don't change when changing language (only on page reload)

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/lagosta#45]
To reproduce:
* go to roas page
* change language

The headers stay the same, even when switching to e.g. parents and back. They change on a page reload though.

Not a big deal, but would be nice to have a fix.

**Comment by enricoberti** [comment]
Is this still valid @timbru ? I cannot repro it

**Comment by timbru** [comment]
I don't think that it is, it's most likely caused by a caching issue - I have found that I have needed to restart my browser to pick up on changes. Maybe there is an issue with etag or what not when Krill serves the static content?

**Comment by timbru** [comment]
Fixed (a while ago, not sure which commit)
