### ISSUE TITLE
Some labels are not translated to other languages

### ISSUE THREAD

**Issue by gthess** [NLnetLabs/lagosta#51]
The following cases are for labels that do not seem to be translatable.
Language change (and even reload with the new language, as #45 suggested) has no impact:

- ROA tab with "BGP info" on -> Under the "allows announcements" section -> **prefix** is not translatable
- ROA tab -> click "add ROA" ->  **prefix** is not translatable
- ROA tab (with no data to show) -> **No data** is not translatable. Easy reproduction for this is to select the trust anchor CA with "BGP info" off. Not sure if this is possible to translate though, may be coming from the framework.

**Comment by enricoberti** [comment]
thanks! closed
