### ISSUE TITLE
Strip whitespace when converting uploaded XML into json (for testbed)

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/lagosta#84]
The Testbed upload pages convert submitted XML into json. The content, in particular the id_cert value, should not contain `\n` - what may work is `\\n`, but stripping all whitespace altogether is probably best. See this issue:
See: https://github.com/NLnetLabs/krill/issues/369

Example of broken submitted json:
{"handle":"aaa","resources":{"asn":"1","v4":"","v6":""},"auth":{"rfc8183":{"tag":null,"child_handle":"aaa","id_cert":"\nMIID2zCCAsOgAwIBAgIRAJ5+L7MLm2FEfAQW484n9MkwDQYJKoZIhvcNAQELBQAwgYYxCzAJBgNV\nBAYTAlVTMRwwGgYDVQQKDBNBbWF6b24gV2ViIFNlcnZpY2VzMRYwFAYDVQQLDA1Ecm9wa2ljayBC\nUEtJMREwDwYDVQQIDAhWaXJnaW5pYTEaMBgGA1UEAwwRd3d3LmFtYXpvbmF3cy5jb20xEjAQBgNV\nBAcMCUFybGluZ3RvbjAeFw0yMTAxMDQyMDQ2MzZaFw0zMTAxMDIyMTQ2MzZaMIGGMQswCQYDVQQG\nEwJVUzEcMBoGA1UECgwTQW1hem9uIFdlYiBTZXJ2aWNlczEWMBQGA1UECwwNRHJvcGtpY2sgQlBL\nSTERMA8GA1UECAwIVmlyZ2luaWExGjAYBgNVBAMMEXd3dy5hbWF6b25hd3MuY29tMRIwEAYDVQQH\nDAlBcmxpbmd0b24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYQ9b0VQEt0ita4ZoD\nUTL5WtXE9hsQ/IxDL7StTpTNpeQXHBZmY+JH9YcLtviFWJ2L0FX4Q2JGw8YMjuju+0WChjGKNuQp\nhx8KKDCC0AFlf31Iy6GYEFMpnePvcWRVNw7gM04c8J5p5rYy+GWKHajqtkLXVBLSi1HDYcUSNvAb\nqCg20FUez2HlVz9kbY/dVYE87q8CCVEkbhHcuoV/WYvKzmbhQ2pWF2mwISrrcLTnIMa5Hq7diKia\nK9w2RJNf8rtW5ADCW6hU17iFfiXLs8Bstkiv9XmnlF1uJbolUieOjc3595Fh8Bvf63bGDOfAuIHw\nCx07u39ztaTZOEWJFR/vAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFK8dD1Fz\nNOnuMPj9nL/rK7aILkIeMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAxoUUBicJ\n9mqbz03teqXH1DBhLkvi5YmSlI/SJ/WjGzS7dLQYeLCi7VZ5yh56tZHU4mhUwWbaOHpwPK5U2+VY\nZ1/HLjXuW4fDJ9hIGHewZd2q4IDURhs9uKoldoqmYD3cLuR4Csmp8vHHqQ8JgnKxRDdmwJcZzGtm\nefN2aNYafo6ujRe/EmL/rQU9SbeYYDi8pEFyedcKPe0Uu3Ar3anSlSaEFdztIWED8n6zyhVKprrh\n7Rvd5koN/dXgSBNObEjnxlOTAx+mDdYisOVkV1ucCAgm9qJ2hnAniqGdydbogocTpG6de/NpPiuW\nSbojMN4+czSxletVel/ofm7wfzJsWQ==\n"}}}

**Comment by ximon18** [comment]
This was addressed in https://github.com/NLnetLabs/krill/issues/369 via Lagosta commit d94470db22792. It isn't yet deployed in production, but it was fixed in Krill and Lagosta code and so this issue can be closed.
